apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev 
resources:
- ../../../../../../base/be
- ./overlays/pod-disruption-budget.yaml
images:
- name: yasminemarzouk/template-be
  newName: docker.io/yasminemarzouk/template-be-dev
  newTag: be-dev

patches:
- path: ./patches/deployment.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
configMapGenerator:
  - name: myconfigmap
    envs:
      - ./generators/config.properties
secretGenerator:
  - name: mysecret
    envs: 
      - ./generators/secret.properties